20 utils.LogMiddleware 2019-05-04 08:51:47,133
20 utils.LogMiddleware 2019-05-04 08:51:47,135
20 utils.LogMiddleware 2019-05-04 08:51:58,156
20 utils.LogMiddleware 2019-05-04 08:51:58,158
20 utils.LogMiddleware 2019-05-04 11:16:17,519
20 utils.LogMiddleware 2019-05-04 11:16:17,520
20 utils.LogMiddleware 2019-05-04 11:18:21,707
20 utils.LogMiddleware 2019-05-04 11:18:21,708
20 utils.LogMiddleware 2019-05-04 11:18:55,976
20 utils.LogMiddleware 2019-05-04 11:18:55,983
20 utils.LogMiddleware 2019-05-04 11:19:35,778
20 utils.LogMiddleware 2019-05-04 11:19:35,779
20 utils.LogMiddleware 2019-05-04 11:20:00,411
20 utils.LogMiddleware 2019-05-04 11:20:00,418
20 utils.LogMiddleware 2019-05-05 04:14:33,532
20 utils.LogMiddleware 2019-05-05 04:14:33,534
20 utils.LogMiddleware 2019-05-05 04:15:01,810
20 utils.LogMiddleware 2019-05-05 04:15:01,813
20 utils.LogMiddleware 2019-05-05 04:15:15,795
20 utils.LogMiddleware 2019-05-05 04:15:15,795
20 utils.LogMiddleware 2019-05-05 04:16:07,401
20 utils.LogMiddleware 2019-05-05 04:16:07,404
20 utils.LogMiddleware 2019-05-05 04:16:38,754
20 utils.LogMiddleware 2019-05-05 04:16:38,755
20 utils.LogMiddleware 2019-05-05 04:16:59,122
20 utils.LogMiddleware 2019-05-05 04:16:59,130
20 utils.LogMiddleware 2019-05-05 04:17:24,954
20 utils.LogMiddleware 2019-05-05 04:17:24,956
20 utils.LogMiddleware 2019-05-05 04:18:20,150
20 utils.LogMiddleware 2019-05-05 04:18:20,154
20 utils.LogMiddleware 2019-05-05 04:18:23,975
20 utils.LogMiddleware 2019-05-05 04:18:23,977
20 utils.LogMiddleware 2019-05-05 04:18:35,184
20 utils.LogMiddleware 2019-05-05 04:18:35,191
20 utils.LogMiddleware 2019-05-05 04:42:11,196
20 utils.LogMiddleware 2019-05-05 04:42:11,199
20 utils.LogMiddleware 2019-05-05 04:42:11,217
20 utils.LogMiddleware 2019-05-05 04:42:11,220
20 utils.LogMiddleware 2019-05-05 04:42:11,240
20 utils.LogMiddleware 2019-05-05 04:42:11,241
20 utils.LogMiddleware 2019-05-05 04:42:17,408
20 utils.LogMiddleware 2019-05-05 04:42:17,415
20 utils.LogMiddleware 2019-05-05 04:42:47,083
20 utils.LogMiddleware 2019-05-05 04:42:47,086
20 utils.LogMiddleware 2019-05-05 04:43:08,926
20 utils.LogMiddleware 2019-05-05 04:43:09,095
30 django.request 2019-05-05 04:43:09,096
20 utils.LogMiddleware 2019-05-05 04:43:17,373
20 utils.LogMiddleware 2019-05-05 04:43:17,381
20 utils.LogMiddleware 2019-05-05 04:45:05,347
20 utils.LogMiddleware 2019-05-05 04:45:05,348
20 utils.LogMiddleware 2019-05-05 04:45:12,007
20 utils.LogMiddleware 2019-05-05 04:45:12,013
20 utils.LogMiddleware 2019-05-05 04:45:14,571
20 utils.LogMiddleware 2019-05-05 04:45:14,574
20 utils.LogMiddleware 2019-05-05 04:45:43,280
20 utils.LogMiddleware 2019-05-05 04:45:43,282
20 utils.LogMiddleware 2019-05-05 04:50:23,628
20 utils.LogMiddleware 2019-05-05 04:50:23,629
20 utils.LogMiddleware 2019-05-05 04:55:36,819
20 utils.LogMiddleware 2019-05-05 04:55:36,820
20 utils.LogMiddleware 2019-05-05 04:56:09,139
20 utils.LogMiddleware 2019-05-05 04:56:09,145
20 utils.LogMiddleware 2019-05-05 04:58:52,152
20 utils.LogMiddleware 2019-05-05 04:58:52,161
20 utils.LogMiddleware 2019-05-05 04:59:14,385
20 utils.LogMiddleware 2019-05-05 04:59:14,395
20 utils.LogMiddleware 2019-05-05 04:59:22,526
20 utils.LogMiddleware 2019-05-05 04:59:22,533
20 utils.LogMiddleware 2019-05-05 05:00:56,525
20 utils.LogMiddleware 2019-05-05 05:00:56,532
20 utils.LogMiddleware 2019-05-05 05:03:13,303
20 utils.LogMiddleware 2019-05-05 05:03:13,304
20 utils.LogMiddleware 2019-05-05 05:03:56,376
20 utils.LogMiddleware 2019-05-05 05:03:56,378
20 utils.LogMiddleware 2019-05-05 05:04:06,971
20 utils.LogMiddleware 2019-05-05 05:04:06,972
20 utils.LogMiddleware 2019-05-05 05:04:36,946
20 utils.LogMiddleware 2019-05-05 05:04:36,947
20 utils.LogMiddleware 2019-05-05 05:04:42,222
20 utils.LogMiddleware 2019-05-05 05:04:42,224
20 utils.LogMiddleware 2019-05-05 05:04:47,079
20 utils.LogMiddleware 2019-05-05 05:04:47,081
20 utils.LogMiddleware 2019-05-05 05:04:51,526
20 utils.LogMiddleware 2019-05-05 05:04:51,528
20 utils.LogMiddleware 2019-05-05 05:05:25,885
20 utils.LogMiddleware 2019-05-05 05:05:25,886
20 utils.LogMiddleware 2019-05-05 05:05:35,284
20 utils.LogMiddleware 2019-05-05 05:05:35,292
20 utils.LogMiddleware 2019-05-05 05:05:40,994
20 utils.LogMiddleware 2019-05-05 05:05:40,995
20 utils.LogMiddleware 2019-05-05 05:05:54,275
20 utils.LogMiddleware 2019-05-05 05:05:54,283
20 utils.LogMiddleware 2019-05-05 05:06:03,235
20 utils.LogMiddleware 2019-05-05 05:06:03,236
20 utils.LogMiddleware 2019-05-05 05:06:35,120
20 utils.LogMiddleware 2019-05-05 05:06:35,121
20 utils.LogMiddleware 2019-05-05 05:08:39,740
20 utils.LogMiddleware 2019-05-05 05:08:39,747
20 utils.LogMiddleware 2019-05-05 05:08:44,269
20 utils.LogMiddleware 2019-05-05 05:08:44,270
20 utils.LogMiddleware 2019-05-05 05:09:56,386
20 utils.LogMiddleware 2019-05-05 05:09:56,394
20 utils.LogMiddleware 2019-05-05 05:10:03,429
20 utils.LogMiddleware 2019-05-05 05:10:03,433
20 utils.LogMiddleware 2019-05-05 05:13:39,065
20 utils.LogMiddleware 2019-05-05 05:13:39,068
20 utils.LogMiddleware 2019-05-05 05:18:10,473
20 utils.LogMiddleware 2019-05-05 05:18:10,480
20 utils.LogMiddleware 2019-05-05 05:22:03,219
20 utils.LogMiddleware 2019-05-05 05:22:03,226
20 utils.LogMiddleware 2019-05-05 05:22:10,016
20 utils.LogMiddleware 2019-05-05 05:22:10,019
20 utils.LogMiddleware 2019-05-05 05:25:47,297
20 utils.LogMiddleware 2019-05-05 05:25:47,297
20 utils.LogMiddleware 2019-05-05 05:26:36,539
20 utils.LogMiddleware 2019-05-05 05:26:36,545
20 utils.LogMiddleware 2019-05-05 05:27:18,167
20 utils.LogMiddleware 2019-05-05 05:27:18,168
20 utils.LogMiddleware 2019-05-05 05:27:26,043
20 utils.LogMiddleware 2019-05-05 05:27:26,044
20 utils.LogMiddleware 2019-05-05 05:28:52,058
20 utils.LogMiddleware 2019-05-05 05:28:52,059
20 utils.LogMiddleware 2019-05-05 05:30:31,198
20 utils.LogMiddleware 2019-05-05 05:30:31,199
20 utils.LogMiddleware 2019-05-05 05:32:03,867
20 utils.LogMiddleware 2019-05-05 05:32:03,870
20 utils.LogMiddleware 2019-05-05 12:36:44,489
20 utils.LogMiddleware 2019-05-05 12:36:44,494
20 utils.LogMiddleware 2019-05-05 12:36:59,508
20 utils.LogMiddleware 2019-05-05 12:36:59,518
20 utils.LogMiddleware 2019-05-05 12:50:55,310
20 utils.LogMiddleware 2019-05-05 12:50:55,311
20 utils.LogMiddleware 2019-05-05 12:51:08,564
20 utils.LogMiddleware 2019-05-05 12:51:08,565
20 utils.LogMiddleware 2019-05-05 12:51:36,692
20 utils.LogMiddleware 2019-05-05 12:51:36,692
20 utils.LogMiddleware 2019-05-05 12:51:41,579
20 utils.LogMiddleware 2019-05-05 12:51:41,581
20 utils.LogMiddleware 2019-05-05 12:52:29,139
20 utils.LogMiddleware 2019-05-05 12:52:29,141
20 utils.LogMiddleware 2019-05-05 12:52:34,797
20 utils.LogMiddleware 2019-05-05 12:52:34,798
20 utils.LogMiddleware 2019-05-05 12:53:11,615
20 utils.LogMiddleware 2019-05-05 12:53:11,616
20 utils.LogMiddleware 2019-05-05 12:55:22,209
20 utils.LogMiddleware 2019-05-05 12:55:22,211
20 utils.LogMiddleware 2019-05-05 12:55:46,729
20 utils.LogMiddleware 2019-05-05 12:55:46,731
20 utils.LogMiddleware 2019-05-05 12:56:10,431
20 utils.LogMiddleware 2019-05-05 12:56:10,434
20 utils.LogMiddleware 2019-05-05 13:00:17,435
20 utils.LogMiddleware 2019-05-05 13:00:17,438
20 utils.LogMiddleware 2019-05-05 13:02:21,136
20 utils.LogMiddleware 2019-05-05 13:02:21,137
20 utils.LogMiddleware 2019-05-05 13:03:19,496
20 utils.LogMiddleware 2019-05-05 13:03:19,498
20 utils.LogMiddleware 2019-05-05 13:03:37,208
20 utils.LogMiddleware 2019-05-05 13:03:37,218
20 utils.LogMiddleware 2019-05-05 13:03:48,930
20 utils.LogMiddleware 2019-05-05 13:03:48,931
20 utils.LogMiddleware 2019-05-05 13:04:10,868
20 utils.LogMiddleware 2019-05-05 13:04:10,869
20 utils.LogMiddleware 2019-05-05 13:04:38,929
20 utils.LogMiddleware 2019-05-05 13:04:38,936
20 utils.LogMiddleware 2019-05-05 13:06:28,007
20 utils.LogMiddleware 2019-05-05 13:06:28,013
20 utils.LogMiddleware 2019-05-05 13:07:00,424
20 utils.LogMiddleware 2019-05-05 13:07:00,432
20 utils.LogMiddleware 2019-05-05 13:07:41,015
20 utils.LogMiddleware 2019-05-05 13:07:41,019
20 utils.LogMiddleware 2019-05-05 13:07:44,995
20 utils.LogMiddleware 2019-05-05 13:07:45,014
20 utils.LogMiddleware 2019-05-05 13:07:53,681
20 utils.LogMiddleware 2019-05-05 13:07:53,682
20 utils.LogMiddleware 2019-05-05 13:08:51,653
20 utils.LogMiddleware 2019-05-05 13:08:51,659
20 utils.LogMiddleware 2019-05-05 13:09:00,883
20 utils.LogMiddleware 2019-05-05 13:09:00,885
20 utils.LogMiddleware 2019-05-05 13:12:03,333
20 utils.LogMiddleware 2019-05-05 13:12:03,335
20 utils.LogMiddleware 2019-05-05 13:12:47,674
20 utils.LogMiddleware 2019-05-05 13:12:47,674
20 utils.LogMiddleware 2019-05-05 13:12:50,070
20 utils.LogMiddleware 2019-05-05 13:12:50,077
20 utils.LogMiddleware 2019-05-05 13:13:24,166
20 utils.LogMiddleware 2019-05-05 13:13:24,167
20 utils.LogMiddleware 2019-05-05 13:13:37,290
20 utils.LogMiddleware 2019-05-05 13:13:42,378
20 utils.LogMiddleware 2019-05-05 13:23:08,506
20 utils.LogMiddleware 2019-05-05 13:23:08,507
20 utils.LogMiddleware 2019-05-05 13:23:59,808
20 utils.LogMiddleware 2019-05-05 13:23:59,811
20 utils.LogMiddleware 2019-05-05 13:27:19,308
20 utils.LogMiddleware 2019-05-05 13:27:19,313
20 utils.LogMiddleware 2019-05-05 13:27:24,348
20 utils.LogMiddleware 2019-05-05 13:27:24,356
20 utils.LogMiddleware 2019-05-05 13:28:10,559
20 utils.LogMiddleware 2019-05-05 13:28:10,560
20 utils.LogMiddleware 2019-05-06 18:24:38,405
20 utils.LogMiddleware 2019-05-06 18:54:58,914
20 utils.LogMiddleware 2019-05-06 18:54:58,916
20 utils.LogMiddleware 2019-05-06 18:57:30,107
20 utils.LogMiddleware 2019-05-06 18:57:30,110
20 utils.LogMiddleware 2019-05-06 19:00:43,560
20 utils.LogMiddleware 2019-05-06 19:01:25,922
20 utils.LogMiddleware 2019-05-06 19:01:55,918
20 utils.LogMiddleware 2019-05-06 19:01:57,543
20 utils.LogMiddleware 2019-05-06 19:02:00,790
20 utils.LogMiddleware 2019-05-06 19:02:55,882
20 utils.LogMiddleware 2019-05-06 19:02:59,143
20 utils.LogMiddleware 2019-05-06 19:03:02,249
20 utils.LogMiddleware 2019-05-06 19:03:28,524
20 utils.LogMiddleware 2019-05-06 19:03:39,532
20 utils.LogMiddleware 2019-05-06 19:03:40,156
20 utils.LogMiddleware 2019-05-06 19:03:43,904
20 utils.LogMiddleware 2019-05-06 19:03:43,906
20 utils.LogMiddleware 2019-05-06 20:35:48,068
20 utils.LogMiddleware 2019-05-07 09:36:29,244
20 utils.LogMiddleware 2019-05-07 09:36:29,250
20 utils.LogMiddleware 2019-05-07 09:36:31,602
20 utils.LogMiddleware 2019-05-07 09:36:33,995
20 utils.LogMiddleware 2019-05-07 09:36:33,998
20 utils.LogMiddleware 2019-05-07 09:36:46,506
20 utils.LogMiddleware 2019-05-07 09:37:02,010
20 utils.LogMiddleware 2019-05-07 09:37:05,977
20 utils.LogMiddleware 2019-05-07 09:37:24,776
20 utils.LogMiddleware 2019-05-07 09:37:26,038
20 utils.LogMiddleware 2019-05-07 09:38:05,032
20 utils.LogMiddleware 2019-05-07 09:38:05,034
20 utils.LogMiddleware 2019-05-07 09:38:07,380
20 utils.LogMiddleware 2019-05-07 09:38:07,380
20 utils.LogMiddleware 2019-05-07 09:39:18,649
20 utils.LogMiddleware 2019-05-07 09:39:24,240
20 utils.LogMiddleware 2019-05-07 09:39:43,202
20 utils.LogMiddleware 2019-05-07 09:39:47,414
20 utils.LogMiddleware 2019-05-07 09:41:05,991
20 utils.LogMiddleware 2019-05-07 09:41:05,994
20 utils.LogMiddleware 2019-05-07 09:41:06,045
20 utils.LogMiddleware 2019-05-07 09:45:24,719
20 utils.LogMiddleware 2019-05-07 09:45:28,094
20 utils.LogMiddleware 2019-05-07 09:46:16,446
30 django.request 2019-05-07 09:46:16,446
20 utils.LogMiddleware 2019-05-07 09:46:53,406
20 utils.LogMiddleware 2019-05-07 09:46:54,292
20 utils.LogMiddleware 2019-05-07 09:47:07,670
20 utils.LogMiddleware 2019-05-07 09:47:19,391
20 utils.LogMiddleware 2019-05-07 09:48:37,368
20 utils.LogMiddleware 2019-05-07 09:48:40,895
20 utils.LogMiddleware 2019-05-07 09:49:28,583
20 utils.LogMiddleware 2019-05-07 09:53:09,159
20 utils.LogMiddleware 2019-05-07 09:53:11,843
20 utils.LogMiddleware 2019-05-07 09:53:39,372
20 utils.LogMiddleware 2019-05-07 09:54:06,998
20 utils.LogMiddleware 2019-05-07 09:54:14,600
20 utils.LogMiddleware 2019-05-07 09:54:16,528
20 utils.LogMiddleware 2019-05-07 09:54:19,087
20 utils.LogMiddleware 2019-05-07 09:54:27,636
20 utils.LogMiddleware 2019-05-07 09:54:31,219
20 utils.LogMiddleware 2019-05-07 09:54:33,315
20 utils.LogMiddleware 2019-05-07 09:54:54,580
20 utils.LogMiddleware 2019-05-07 09:55:25,210
20 utils.LogMiddleware 2019-05-07 09:55:37,879
20 utils.LogMiddleware 2019-05-07 09:55:40,425
20 utils.LogMiddleware 2019-05-07 09:56:50,409
20 utils.LogMiddleware 2019-05-07 09:57:42,211
20 utils.LogMiddleware 2019-05-07 09:57:46,080
20 utils.LogMiddleware 2019-05-07 09:57:48,347
20 utils.LogMiddleware 2019-05-07 09:57:50,590
20 utils.LogMiddleware 2019-05-07 09:57:52,021
20 utils.LogMiddleware 2019-05-07 09:58:03,269
20 utils.LogMiddleware 2019-05-07 09:58:45,096
20 utils.LogMiddleware 2019-05-07 10:00:51,587
20 utils.LogMiddleware 2019-05-07 10:03:02,725
20 utils.LogMiddleware 2019-05-07 10:03:56,049
20 utils.LogMiddleware 2019-05-07 10:04:02,470
20 utils.LogMiddleware 2019-05-07 10:04:10,618
20 utils.LogMiddleware 2019-05-07 10:04:29,782
20 utils.LogMiddleware 2019-05-07 10:04:32,905
20 utils.LogMiddleware 2019-05-07 10:04:39,086
20 utils.LogMiddleware 2019-05-07 10:04:49,582
20 utils.LogMiddleware 2019-05-07 10:04:51,912
20 utils.LogMiddleware 2019-05-07 10:04:55,531
20 utils.LogMiddleware 2019-05-07 10:04:58,289
20 utils.LogMiddleware 2019-05-07 10:05:01,297
20 utils.LogMiddleware 2019-05-07 10:05:05,268
20 utils.LogMiddleware 2019-05-07 10:05:08,807
20 utils.LogMiddleware 2019-05-07 10:05:12,756
20 utils.LogMiddleware 2019-05-07 10:05:15,437
20 utils.LogMiddleware 2019-05-07 10:05:18,560
20 utils.LogMiddleware 2019-05-07 10:06:43,315
20 utils.LogMiddleware 2019-05-07 10:06:45,244
20 utils.LogMiddleware 2019-05-07 10:06:48,871
20 utils.LogMiddleware 2019-05-07 10:06:52,089
20 utils.LogMiddleware 2019-05-07 10:06:54,070
20 utils.LogMiddleware 2019-05-07 10:07:03,723
20 utils.LogMiddleware 2019-05-07 10:07:05,918
20 utils.LogMiddleware 2019-05-07 10:07:31,218
20 utils.LogMiddleware 2019-05-07 10:07:34,479
20 utils.LogMiddleware 2019-05-07 10:07:39,975
20 utils.LogMiddleware 2019-05-07 10:07:40,017
20 utils.LogMiddleware 2019-05-07 10:07:43,924
20 utils.LogMiddleware 2019-05-07 10:07:52,004
20 utils.LogMiddleware 2019-05-07 10:07:52,044
20 utils.LogMiddleware 2019-05-07 10:07:54,260
20 utils.LogMiddleware 2019-05-07 10:12:01,521
20 utils.LogMiddleware 2019-05-07 10:12:07,770
20 utils.LogMiddleware 2019-05-07 10:12:47,984
20 utils.LogMiddleware 2019-05-07 10:12:48,059
20 utils.LogMiddleware 2019-05-07 10:12:52,378
20 utils.LogMiddleware 2019-05-07 10:13:12,940
20 utils.LogMiddleware 2019-05-07 10:13:29,926
20 utils.LogMiddleware 2019-05-07 10:13:30,038
20 utils.LogMiddleware 2019-05-07 10:13:34,309
20 utils.LogMiddleware 2019-05-07 10:14:12,712
20 utils.LogMiddleware 2019-05-07 10:14:14,496
20 utils.LogMiddleware 2019-05-07 10:14:22,391
20 utils.LogMiddleware 2019-05-07 10:14:22,463
20 utils.LogMiddleware 2019-05-07 10:14:27,674
20 utils.LogMiddleware 2019-05-07 10:14:30,039
20 utils.LogMiddleware 2019-05-15 11:19:43,396
20 utils.LogMiddleware 2019-05-15 11:19:43,397
20 utils.LogMiddleware 2019-05-15 11:19:44,982
20 utils.LogMiddleware 2019-05-15 11:20:02,958
20 utils.LogMiddleware 2019-05-15 11:20:04,232
20 utils.LogMiddleware 2019-05-15 11:20:05,967
20 utils.LogMiddleware 2019-05-15 11:21:45,386
20 utils.LogMiddleware 2019-05-15 11:21:45,430
20 utils.LogMiddleware 2019-05-15 11:21:49,173
20 utils.LogMiddleware 2019-05-15 11:21:49,174
20 utils.LogMiddleware 2019-05-15 11:21:50,825
20 utils.LogMiddleware 2019-05-15 11:22:55,674
20 utils.LogMiddleware 2019-05-15 11:23:00,220
20 utils.LogMiddleware 2019-05-15 11:23:47,810
20 utils.LogMiddleware 2019-05-15 11:24:18,252
20 utils.LogMiddleware 2019-05-15 11:24:23,414
20 utils.LogMiddleware 2019-05-15 11:24:27,026
20 utils.LogMiddleware 2019-05-15 11:24:28,310
20 utils.LogMiddleware 2019-05-15 11:27:04,606
20 utils.LogMiddleware 2019-05-15 11:30:24,372
20 utils.LogMiddleware 2019-05-15 11:31:27,139
20 utils.LogMiddleware 2019-05-15 11:32:48,251
20 utils.LogMiddleware 2019-05-15 11:39:11,964
20 utils.LogMiddleware 2019-05-15 11:39:16,125
20 utils.LogMiddleware 2019-05-15 11:42:49,005
20 utils.LogMiddleware 2019-05-15 11:43:07,525
20 utils.LogMiddleware 2019-05-15 11:45:11,765
20 utils.LogMiddleware 2019-05-15 11:45:33,025
20 utils.LogMiddleware 2019-05-15 11:45:41,829
20 utils.LogMiddleware 2019-05-15 11:45:46,507
20 utils.LogMiddleware 2019-05-15 11:46:02,088
20 utils.LogMiddleware 2019-05-15 11:46:03,995
20 utils.LogMiddleware 2019-05-15 11:46:17,541
20 utils.LogMiddleware 2019-05-15 11:47:18,985
20 utils.LogMiddleware 2019-05-15 11:49:04,215
20 utils.LogMiddleware 2019-07-08 05:16:11,028
20 utils.LogMiddleware 2019-07-08 05:16:11,030
20 utils.LogMiddleware 2019-07-08 05:16:47,847
20 utils.LogMiddleware 2019-07-08 05:16:49,677
20 utils.LogMiddleware 2019-07-08 05:16:53,413
20 utils.LogMiddleware 2019-07-08 05:17:08,593
20 utils.LogMiddleware 2019-07-08 05:18:30,832
20 utils.LogMiddleware 2019-07-08 05:18:33,247
20 utils.LogMiddleware 2019-07-08 05:18:37,646
20 utils.LogMiddleware 2019-07-08 05:18:39,072
20 utils.LogMiddleware 2019-07-08 05:18:52,686
20 utils.LogMiddleware 2019-07-08 05:18:55,267
20 utils.LogMiddleware 2019-07-08 05:22:03,989
20 utils.LogMiddleware 2019-07-08 05:23:17,739
20 utils.LogMiddleware 2019-07-08 05:24:48,282
20 utils.LogMiddleware 2019-07-08 05:24:52,863
20 utils.LogMiddleware 2019-07-08 05:24:53,816
20 utils.LogMiddleware 2019-07-08 05:24:56,749
20 utils.LogMiddleware 2019-07-08 05:24:57,078
20 utils.LogMiddleware 2019-07-08 05:25:02,543
20 utils.LogMiddleware 2019-07-08 05:25:02,731
20 utils.LogMiddleware 2019-07-08 05:27:40,879
20 utils.LogMiddleware 2019-07-08 05:27:44,038
20 utils.LogMiddleware 2019-07-08 05:27:47,884
20 utils.LogMiddleware 2019-07-08 05:29:57,978
20 utils.LogMiddleware 2019-07-08 05:29:58,025
20 utils.LogMiddleware 2019-07-08 05:30:10,822
20 utils.LogMiddleware 2019-07-08 05:30:10,823
20 utils.LogMiddleware 2019-07-08 05:30:12,801
20 utils.LogMiddleware 2019-07-08 05:30:45,538
20 utils.LogMiddleware 2019-07-08 05:30:45,538
20 utils.LogMiddleware 2019-07-08 05:30:49,160
20 utils.LogMiddleware 2019-07-08 05:30:51,740
20 utils.LogMiddleware 2019-07-08 05:31:20,755
20 utils.LogMiddleware 2019-07-08 05:31:24,068
20 utils.LogMiddleware 2019-07-08 05:31:27,684
20 utils.LogMiddleware 2019-07-08 05:31:33,836
20 utils.LogMiddleware 2019-07-08 05:31:33,883
20 utils.LogMiddleware 2019-07-08 05:31:45,014
20 utils.LogMiddleware 2019-07-08 05:31:49,630
20 utils.LogMiddleware 2019-07-08 05:31:53,012
20 utils.LogMiddleware 2019-07-08 05:32:28,464
20 utils.LogMiddleware 2019-07-08 05:32:31,083
20 utils.LogMiddleware 2019-07-08 05:32:34,084
20 utils.LogMiddleware 2019-07-08 05:32:34,174
40 django.request 2019-07-08 05:33:21,704
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '65432' for key 'title'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/back/views.py", line 28, in create
    data = serializers.create_questions(serializers.data, request.user)
  File "/Users/coco/my_wordspace/answer_django/answer_django/back/serializers.py", line 60, in create_questions
    user=user)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/query.py", line 417, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '65432' for key 'title'")
20 utils.LogMiddleware 2019-07-08 05:33:21,813
20 utils.LogMiddleware 2019-07-08 05:33:30,881
20 utils.LogMiddleware 2019-07-08 05:33:33,095
20 utils.LogMiddleware 2019-07-08 05:33:56,074
20 utils.LogMiddleware 2019-07-08 05:33:58,326
20 utils.LogMiddleware 2019-07-08 05:34:45,429
20 utils.LogMiddleware 2019-07-08 05:34:47,504
20 utils.LogMiddleware 2019-07-08 05:36:14,951
20 utils.LogMiddleware 2019-07-08 05:36:16,773
20 utils.LogMiddleware 2019-07-08 05:36:30,552
20 utils.LogMiddleware 2019-07-08 05:36:41,865
20 utils.LogMiddleware 2019-07-08 05:37:00,488
20 utils.LogMiddleware 2019-07-08 05:37:11,771
20 utils.LogMiddleware 2019-07-08 05:37:16,163
20 utils.LogMiddleware 2019-07-08 05:37:25,919
20 utils.LogMiddleware 2019-07-08 05:37:33,487
20 utils.LogMiddleware 2019-07-08 05:38:09,248
20 utils.LogMiddleware 2019-07-08 05:38:14,688
20 utils.LogMiddleware 2019-07-08 05:39:20,218
20 utils.LogMiddleware 2019-07-08 05:39:20,486
20 utils.LogMiddleware 2019-07-08 05:40:31,225
20 utils.LogMiddleware 2019-07-08 05:40:32,439
20 utils.LogMiddleware 2019-07-08 05:40:35,937
20 utils.LogMiddleware 2019-07-08 05:40:36,489
20 utils.LogMiddleware 2019-07-08 05:40:41,769
20 utils.LogMiddleware 2019-07-08 05:40:42,154
20 utils.LogMiddleware 2019-07-09 04:19:54,918
20 utils.LogMiddleware 2019-07-09 04:19:54,922
20 utils.LogMiddleware 2019-07-09 04:20:00,752
30 django.request 2019-07-09 04:20:00,752
40 django.request 2019-07-09 04:20:24,961
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 04:20:24,991
20 utils.LogMiddleware 2019-07-09 04:20:38,058
40 django.request 2019-07-09 04:20:43,215
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 04:20:43,228
40 django.request 2019-07-09 04:20:47,418
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 04:20:47,431
20 utils.LogMiddleware 2019-07-09 04:21:28,322
20 utils.LogMiddleware 2019-07-09 04:21:33,768
20 utils.LogMiddleware 2019-07-09 04:21:34,543
40 django.request 2019-07-09 04:21:40,302
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 04:21:40,313
20 utils.LogMiddleware 2019-07-09 04:31:25,354
20 utils.LogMiddleware 2019-07-09 04:31:28,922
20 utils.LogMiddleware 2019-07-09 05:07:44,140
20 utils.LogMiddleware 2019-07-09 05:07:45,648
20 utils.LogMiddleware 2019-07-09 05:08:56,619
20 utils.LogMiddleware 2019-07-09 05:09:19,794
40 django.request 2019-07-09 05:09:25,717
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 05:09:25,766
40 django.request 2019-07-09 05:10:15,870
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 149, in set
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/views.py", line 29, in login
    data = serializer.login_data(serializer.data)
  File "/Users/coco/my_wordspace/answer_django/answer_django/user/serializers.py", line 50, in login_data
    cache.set(token, user.id, timeout=60 * 60 * 7 * 24)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django_redis/client/default.py", line 143, in set
    return client.set(nkey, nvalue, nx=nx, px=timeout, xx=xx)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
20 utils.LogMiddleware 2019-07-09 05:10:15,941
20 utils.LogMiddleware 2019-07-09 05:29:28,071
20 utils.LogMiddleware 2019-07-09 05:29:31,249
20 utils.LogMiddleware 2019-07-09 05:30:23,118
20 utils.LogMiddleware 2019-07-09 05:30:24,412
20 utils.LogMiddleware 2019-07-09 05:31:40,620
20 utils.LogMiddleware 2019-07-09 05:31:40,624
20 utils.LogMiddleware 2019-07-09 05:31:40,644
20 utils.LogMiddleware 2019-07-09 05:32:17,854
20 utils.LogMiddleware 2019-07-09 05:32:17,863
20 utils.LogMiddleware 2019-07-09 05:32:17,885
20 utils.LogMiddleware 2019-07-09 05:32:58,072
20 utils.LogMiddleware 2019-07-09 10:16:35,249
20 utils.LogMiddleware 2019-07-09 10:16:46,348
20 utils.LogMiddleware 2019-07-09 10:16:53,854
20 utils.LogMiddleware 2019-07-09 10:16:55,208
20 utils.LogMiddleware 2019-07-09 10:17:01,889
20 utils.LogMiddleware 2019-07-09 10:17:07,318
20 utils.LogMiddleware 2019-07-09 10:17:08,721
20 utils.LogMiddleware 2019-07-09 15:14:33,371
20 utils.LogMiddleware 2019-07-09 15:14:49,593
20 utils.LogMiddleware 2019-07-09 15:14:52,051
20 utils.LogMiddleware 2019-07-09 15:15:34,424
20 utils.LogMiddleware 2019-07-09 15:16:54,431
20 utils.LogMiddleware 2019-07-09 15:17:00,424
20 utils.LogMiddleware 2019-07-09 15:17:04,528
20 utils.LogMiddleware 2019-07-09 15:17:06,726
20 utils.LogMiddleware 2019-07-09 15:17:26,270
20 utils.LogMiddleware 2019-07-09 15:32:27,611
20 utils.LogMiddleware 2019-07-09 15:32:52,037
20 utils.LogMiddleware 2019-07-09 15:33:36,085
20 utils.LogMiddleware 2019-07-09 15:33:37,584
20 utils.LogMiddleware 2019-07-09 15:33:40,625
20 utils.LogMiddleware 2019-07-09 15:33:42,885
20 utils.LogMiddleware 2019-07-09 15:36:00,817
20 utils.LogMiddleware 2019-07-09 15:36:20,812
20 utils.LogMiddleware 2019-07-09 15:39:34,668
20 utils.LogMiddleware 2019-07-09 15:40:36,963
20 utils.LogMiddleware 2019-07-09 15:40:57,102
20 utils.LogMiddleware 2019-07-10 03:54:16,881
20 utils.LogMiddleware 2019-07-10 03:56:44,923
20 utils.LogMiddleware 2019-07-10 03:57:42,118
20 utils.LogMiddleware 2019-07-10 04:01:48,676
20 utils.LogMiddleware 2019-07-10 04:12:23,825
20 utils.LogMiddleware 2019-07-10 04:12:37,750
20 utils.LogMiddleware 2019-07-10 04:13:40,437
20 utils.LogMiddleware 2019-07-10 04:13:46,273
20 utils.LogMiddleware 2019-07-10 04:15:34,577
20 utils.LogMiddleware 2019-07-10 04:17:14,163
20 utils.LogMiddleware 2019-07-10 04:17:41,413
20 utils.LogMiddleware 2019-07-10 04:18:06,155
20 utils.LogMiddleware 2019-07-10 04:18:24,119
20 utils.LogMiddleware 2019-07-10 04:18:41,842
20 utils.LogMiddleware 2019-07-10 04:19:13,319
20 utils.LogMiddleware 2019-07-10 04:19:21,040
20 utils.LogMiddleware 2019-07-10 04:21:10,318
20 utils.LogMiddleware 2019-07-10 04:21:29,544
20 utils.LogMiddleware 2019-07-10 04:21:39,985
20 utils.LogMiddleware 2019-07-10 04:21:47,664
20 utils.LogMiddleware 2019-07-10 04:22:20,277
20 utils.LogMiddleware 2019-07-10 04:23:00,457
20 utils.LogMiddleware 2019-07-10 09:33:03,803
20 utils.LogMiddleware 2019-07-10 09:50:56,387
20 utils.LogMiddleware 2019-07-10 09:50:57,905
20 utils.LogMiddleware 2019-07-10 09:52:13,769
20 utils.LogMiddleware 2019-07-10 09:53:03,336
20 utils.LogMiddleware 2019-07-10 10:04:25,410
20 utils.LogMiddleware 2019-07-10 10:13:19,878
20 utils.LogMiddleware 2019-07-10 10:14:05,890
20 utils.LogMiddleware 2019-07-10 10:14:34,377
20 utils.LogMiddleware 2019-07-10 10:18:17,128
20 utils.LogMiddleware 2019-07-10 10:19:55,321
20 utils.LogMiddleware 2019-07-10 10:21:19,894
20 utils.LogMiddleware 2019-07-10 10:21:54,726
20 utils.LogMiddleware 2019-07-10 10:22:12,435
20 utils.LogMiddleware 2019-07-10 10:24:01,523
20 utils.LogMiddleware 2019-07-10 10:24:16,034
20 utils.LogMiddleware 2019-07-10 10:24:17,002
20 utils.LogMiddleware 2019-07-10 10:24:20,259
20 utils.LogMiddleware 2019-07-10 10:24:51,959
20 utils.LogMiddleware 2019-07-10 10:24:58,342
20 utils.LogMiddleware 2019-07-10 10:25:03,391
20 utils.LogMiddleware 2019-07-10 10:25:04,778
20 utils.LogMiddleware 2019-07-10 10:29:13,890
20 utils.LogMiddleware 2019-07-10 10:29:25,410
20 utils.LogMiddleware 2019-07-10 10:29:34,961
20 utils.LogMiddleware 2019-07-10 10:29:39,351
20 utils.LogMiddleware 2019-07-10 10:29:45,289
20 utils.LogMiddleware 2019-07-10 10:30:22,022
20 utils.LogMiddleware 2019-07-10 10:31:24,280
20 utils.LogMiddleware 2019-07-10 10:31:31,538
20 utils.LogMiddleware 2019-07-10 10:32:11,518
20 utils.LogMiddleware 2019-07-10 10:32:16,931
20 utils.LogMiddleware 2019-07-10 10:32:20,358
20 utils.LogMiddleware 2019-07-13 06:16:15,204
20 utils.LogMiddleware 2019-07-13 06:16:23,799
20 utils.LogMiddleware 2019-07-13 06:16:43,467
20 utils.LogMiddleware 2019-07-13 06:16:49,668
20 utils.LogMiddleware 2019-07-13 06:16:51,616
20 utils.LogMiddleware 2019-07-13 06:17:44,385
20 utils.LogMiddleware 2019-07-13 06:17:47,476
20 utils.LogMiddleware 2019-07-13 06:17:58,349
20 utils.LogMiddleware 2019-07-13 06:17:58,350
20 utils.LogMiddleware 2019-07-13 06:18:31,871
20 utils.LogMiddleware 2019-07-13 06:27:51,094
20 utils.LogMiddleware 2019-07-13 06:27:51,098
20 utils.LogMiddleware 2019-07-13 06:46:46,775
20 utils.LogMiddleware 2019-07-13 06:46:58,237
20 utils.LogMiddleware 2019-07-13 06:46:58,242
20 utils.LogMiddleware 2019-07-13 06:51:02,250
20 utils.LogMiddleware 2019-07-13 06:51:23,679
40 django.request 2019-07-13 06:51:36,211
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: count() takes 1 positional argument but 2 were given
20 utils.LogMiddleware 2019-07-13 06:51:36,255
40 django.request 2019-07-13 06:52:17,362
Traceback (most recent call last):
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coco/env/lesouenv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: count() takes 1 positional argument but 2 were given
20 utils.LogMiddleware 2019-07-13 06:52:17,375
20 utils.LogMiddleware 2019-07-13 06:52:31,434
20 utils.LogMiddleware 2019-07-13 06:54:15,610
